#!/usr/bin/env sh
set -eu

make_temp_file() {
  mktemp $1/tmp-XXXXXXXX
}

base_directory() {
  dirname $1
}

freeze_script() {
  $1/freeze
}

output_to_file() {
  cat >$1
}

make_executable() {
  chmod u+x $1
}

run() {
  make_executable $1
  $1 "$@"
}

remove_file() {
  rm -f $1
}

main() {
  local dir=$(base_directory $1)
  shift
  local file=$(make_temp_file $dir)
  freeze_script $dir | output_to_file $file
  run $file "$@"
  local status=$?
  remove_file $file
  return $status
}

set -eu
main $0 "$@"
